package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Carrom Piece & Game Accent Colors
val CarromQueenRed = Color(0xFFD32F2F)
val CarromQueenGold = Color(0xFFFFB300)
val CarromWhiteCoin = Color(0xFFFAF7F2)
val CarromBlackCoin = Color(0xFF212121)
val CarromWhiteBorder = Color(0xFFBCAAA4)
val CarromBlackBorder = Color(0xFF424242)

// ==========================================
// 1. MINIMAL SLATE (Modern Monochrome)
// ==========================================
val SlatePrimaryLight = Color(0xFF1E293B)
val SlateOnPrimaryLight = Color(0xFFFFFFFF)
val SlatePrimaryContainerLight = Color(0xFFF1F5F9)
val SlateOnPrimaryContainerLight = Color(0xFF0F172A)
val SlateSecondaryLight = Color(0xFF475569)
val SlateOnSecondaryLight = Color(0xFFFFFFFF)
val SlateSecondaryContainerLight = Color(0xFFE2E8F0)
val SlateOnSecondaryContainerLight = Color(0xFF1E293B)
val SlateTertiaryLight = Color(0xFF0284C7)
val SlateOnTertiaryLight = Color(0xFFFFFFFF)
val SlateTertiaryContainerLight = Color(0xFFE0F2FE)
val SlateOnTertiaryContainerLight = Color(0xFF0369A1)
val SlateBackgroundLight = Color(0xFFF8FAFC)
val SlateOnBackgroundLight = Color(0xFF0F172A)
val SlateSurfaceLight = Color(0xFFFFFFFF)
val SlateOnSurfaceLight = Color(0xFF0F172A)
val SlateSurfaceVariantLight = Color(0xFFF1F5F9)
val SlateOnSurfaceVariantLight = Color(0xFF475569)
val SlateOutlineLight = Color(0xFFCBD5E1)

val SlatePrimaryDark = Color(0xFFF8FAFC)
val SlateOnPrimaryDark = Color(0xFF0F172A)
val SlatePrimaryContainerDark = Color(0xFF334155)
val SlateOnPrimaryContainerDark = Color(0xFFF8FAFC)
val SlateSecondaryDark = Color(0xFF94A3B8)
val SlateOnSecondaryDark = Color(0xFF0F172A)
val SlateSecondaryContainerDark = Color(0xFF1E293B)
val SlateOnSecondaryContainerDark = Color(0xFFE2E8F0)
val SlateTertiaryDark = Color(0xFF38BDF8)
val SlateOnTertiaryDark = Color(0xFF082F49)
val SlateTertiaryContainerDark = Color(0xFF075985)
val SlateOnTertiaryContainerDark = Color(0xFFE0F2FE)
val SlateBackgroundDark = Color(0xFF0B0F17)
val SlateOnBackgroundDark = Color(0xFFF1F5F9)
val SlateSurfaceDark = Color(0xFF131824)
val SlateOnSurfaceDark = Color(0xFFF1F5F9)
val SlateSurfaceVariantDark = Color(0xFF1E2638)
val SlateOnSurfaceVariantDark = Color(0xFF94A3B8)
val SlateOutlineDark = Color(0xFF334155)

// ==========================================
// 2. NORDIC IVORY (Warm Minimal / Linen & Sand)
// ==========================================
val IvoryPrimaryLight = Color(0xFF3E3832)
val IvoryOnPrimaryLight = Color(0xFFFFFFFF)
val IvoryPrimaryContainerLight = Color(0xFFEFEBE4)
val IvoryOnPrimaryContainerLight = Color(0xFF24211D)
val IvorySecondaryLight = Color(0xFF756B60)
val IvoryOnSecondaryLight = Color(0xFFFFFFFF)
val IvorySecondaryContainerLight = Color(0xFFE5DFD6)
val IvoryOnSecondaryContainerLight = Color(0xFF2C261F)
val IvoryTertiaryLight = Color(0xFF8C6D46)
val IvoryOnTertiaryLight = Color(0xFFFFFFFF)
val IvoryTertiaryContainerLight = Color(0xFFF4ECE1)
val IvoryOnTertiaryContainerLight = Color(0xFF352511)
val IvoryBackgroundLight = Color(0xFFFAF8F5)
val IvoryOnBackgroundLight = Color(0xFF201C18)
val IvorySurfaceLight = Color(0xFFFFFFFF)
val IvoryOnSurfaceLight = Color(0xFF201C18)
val IvorySurfaceVariantLight = Color(0xFFEFEBE4)
val IvoryOnSurfaceVariantLight = Color(0xFF5C544B)
val IvoryOutlineLight = Color(0xFFD8CFBE)

val IvoryPrimaryDark = Color(0xFFEDE5D8)
val IvoryOnPrimaryDark = Color(0xFF26211B)
val IvoryPrimaryContainerDark = Color(0xFF3B332B)
val IvoryOnPrimaryContainerDark = Color(0xFFFAF6F0)
val IvorySecondaryDark = Color(0xFFC9BDAE)
val IvoryOnSecondaryDark = Color(0xFF26211B)
val IvorySecondaryContainerDark = Color(0xFF302A24)
val IvoryOnSecondaryContainerDark = Color(0xFFEDE5D8)
val IvoryTertiaryDark = Color(0xFFDEC3A3)
val IvoryOnTertiaryDark = Color(0xFF332210)
val IvoryTertiaryContainerDark = Color(0xFF4D381E)
val IvoryOnTertiaryContainerDark = Color(0xFFFCEFD8)
val IvoryBackgroundDark = Color(0xFF141210)
val IvoryOnBackgroundDark = Color(0xFFEDE5D8)
val IvorySurfaceDark = Color(0xFF1C1916)
val IvoryOnSurfaceDark = Color(0xFFEDE5D8)
val IvorySurfaceVariantDark = Color(0xFF2C2621)
val IvoryOnSurfaceVariantDark = Color(0xFFC9BDAE)
val IvoryOutlineDark = Color(0xFF463E35)

// ==========================================
// 3. MIDNIGHT OBSIDIAN (Pure OLED Minimal)
// ==========================================
val ObsidianPrimaryLight = Color(0xFF000000)
val ObsidianOnPrimaryLight = Color(0xFFFFFFFF)
val ObsidianPrimaryContainerLight = Color(0xFFF0F0F0)
val ObsidianOnPrimaryContainerLight = Color(0xFF000000)
val ObsidianSecondaryLight = Color(0xFF404040)
val ObsidianOnSecondaryLight = Color(0xFFFFFFFF)
val ObsidianSecondaryContainerLight = Color(0xFFE5E5E5)
val ObsidianOnSecondaryContainerLight = Color(0xFF171717)
val ObsidianTertiaryLight = Color(0xFF059669)
val ObsidianOnTertiaryLight = Color(0xFFFFFFFF)
val ObsidianTertiaryContainerLight = Color(0xFFD1FAE5)
val ObsidianOnTertiaryContainerLight = Color(0xFF064E3B)
val ObsidianBackgroundLight = Color(0xFFFCFCFC)
val ObsidianOnBackgroundLight = Color(0xFF0A0A0A)
val ObsidianSurfaceLight = Color(0xFFFFFFFF)
val ObsidianOnSurfaceLight = Color(0xFF0A0A0A)
val ObsidianSurfaceVariantLight = Color(0xFFF3F3F3)
val ObsidianOnSurfaceVariantLight = Color(0xFF525252)
val ObsidianOutlineLight = Color(0xFFD4D4D4)

val ObsidianPrimaryDark = Color(0xFFFFFFFF)
val ObsidianOnPrimaryDark = Color(0xFF000000)
val ObsidianPrimaryContainerDark = Color(0xFF262626)
val ObsidianOnPrimaryContainerDark = Color(0xFFFFFFFF)
val ObsidianSecondaryDark = Color(0xFFA3A3A3)
val ObsidianOnSecondaryDark = Color(0xFF000000)
val ObsidianSecondaryContainerDark = Color(0xFF1F1F1F)
val ObsidianOnSecondaryContainerDark = Color(0xFFE5E5E5)
val ObsidianTertiaryDark = Color(0xFF34D399)
val ObsidianOnTertiaryDark = Color(0xFF022C22)
val ObsidianTertiaryContainerDark = Color(0xFF065F46)
val ObsidianOnTertiaryContainerDark = Color(0xFFA7F3D0)
val ObsidianBackgroundDark = Color(0xFF000000)
val ObsidianOnBackgroundDark = Color(0xFFEDEDED)
val ObsidianSurfaceDark = Color(0xFF0E0E0E)
val ObsidianOnSurfaceDark = Color(0xFFEDEDED)
val ObsidianSurfaceVariantDark = Color(0xFF1A1A1A)
val ObsidianOnSurfaceVariantDark = Color(0xFFA3A3A3)
val ObsidianOutlineDark = Color(0xFF2E2E2E)

// ==========================================
// 4. ZEN SAGE (Calming Minimal)
// ==========================================
val SagePrimaryLight = Color(0xFF28443B)
val SageOnPrimaryLight = Color(0xFFFFFFFF)
val SagePrimaryContainerLight = Color(0xFFE2ECE7)
val SageOnPrimaryContainerLight = Color(0xFF102820)
val SageSecondaryLight = Color(0xFF486057)
val SageOnSecondaryLight = Color(0xFFFFFFFF)
val SageSecondaryContainerLight = Color(0xFFD4E2DC)
val SageOnSecondaryContainerLight = Color(0xFF1F2E29)
val SageTertiaryLight = Color(0xFF607252)
val SageOnTertiaryLight = Color(0xFFFFFFFF)
val SageTertiaryContainerLight = Color(0xFFE4EBDC)
val SageOnTertiaryContainerLight = Color(0xFF212C17)
val SageBackgroundLight = Color(0xFFF7FAF8)
val SageOnBackgroundLight = Color(0xFF18221D)
val SageSurfaceLight = Color(0xFFFFFFFF)
val SageOnSurfaceLight = Color(0xFF18221D)
val SageSurfaceVariantLight = Color(0xFFE3ECE7)
val SageOnSurfaceVariantLight = Color(0xFF46574F)
val SageOutlineLight = Color(0xFFCAD6D0)

val SagePrimaryDark = Color(0xFF9ECBB9)
val SageOnPrimaryDark = Color(0xFF0F2F24)
val SagePrimaryContainerDark = Color(0xFF234237)
val SageOnPrimaryContainerDark = Color(0xFFC2E5D6)
val SageSecondaryDark = Color(0xFFADC5BC)
val SageOnSecondaryDark = Color(0xFF182F26)
val SageSecondaryContainerDark = Color(0xFF293F36)
val SageOnSecondaryContainerDark = Color(0xFFD7E7E0)
val SageTertiaryDark = Color(0xFFBED4A9)
val SageOnTertiaryDark = Color(0xFF253516)
val SageTertiaryContainerDark = Color(0xFF394B29)
val SageOnTertiaryContainerDark = Color(0xFFDEF0CD)
val SageBackgroundDark = Color(0xFF0C1411)
val SageOnBackgroundDark = Color(0xFFE4EEE9)
val SageSurfaceDark = Color(0xFF121C18)
val SageOnSurfaceDark = Color(0xFFE4EEE9)
val SageSurfaceVariantDark = Color(0xFF1E2B25)
val SageOnSurfaceVariantDark = Color(0xFFADC5BC)
val SageOutlineDark = Color(0xFF2D3F37)

// ==========================================
// 5. CLASSIC CARROM (Amber & Wood Heritage)
// ==========================================
val WoodDark = Color(0xFF2C1810)
val WoodMedium = Color(0xFF5D3A1A)
val WoodLight = Color(0xFF8B5A2B)
val CarromBoardCream = Color(0xFFF9F3EB)
val CarromBoardDark = Color(0xFF1E1713)

val AmberPrimaryLight = Color(0xFF8A5100)
val AmberOnPrimaryLight = Color(0xFFFFFFFF)
val AmberPrimaryContainerLight = Color(0xFFFFDDB8)
val AmberOnPrimaryContainerLight = Color(0xFF2C1600)
val AmberSecondaryLight = Color(0xFF715A42)
val AmberOnSecondaryLight = Color(0xFFFFFFFF)
val AmberSecondaryContainerLight = Color(0xFFFCDDC1)
val AmberOnSecondaryContainerLight = Color(0xFF281806)
val AmberTertiaryLight = Color(0xFF55633C)
val AmberOnTertiaryLight = Color(0xFFFFFFFF)
val AmberTertiaryContainerLight = Color(0xFFD8E9B7)
val AmberOnTertiaryContainerLight = Color(0xFF131F02)
val AmberBackgroundLight = Color(0xFFFFF8F4)
val AmberOnBackgroundLight = Color(0xFF211A14)
val AmberSurfaceLight = Color(0xFFFFF8F4)
val AmberOnSurfaceLight = Color(0xFF211A14)
val AmberSurfaceVariantLight = Color(0xFFF1DFD0)
val AmberOnSurfaceVariantLight = Color(0xFF50453A)
val AmberOutlineLight = Color(0xFF837568)

val AmberPrimaryDark = Color(0xFFFFB86F)
val AmberOnPrimaryDark = Color(0xFF4A2800)
val AmberPrimaryContainerDark = Color(0xFF693C00)
val AmberOnPrimaryContainerDark = Color(0xFFFFDDB8)
val AmberSecondaryDark = Color(0xFFDFC1A6)
val AmberOnSecondaryDark = Color(0xFF3F2D18)
val AmberSecondaryContainerDark = Color(0xFF57432D)
val AmberOnSecondaryContainerDark = Color(0xFFFCDDC1)
val AmberTertiaryDark = Color(0xFFBCCD9D)
val AmberOnTertiaryDark = Color(0xFF283512)
val AmberTertiaryContainerDark = Color(0xFF3E4B27)
val AmberOnTertiaryContainerDark = Color(0xFFD8E9B7)
val AmberBackgroundDark = Color(0xFF19120C)
val AmberOnBackgroundDark = Color(0xFFEFE0D5)
val AmberSurfaceDark = Color(0xFF19120C)
val AmberOnSurfaceDark = Color(0xFFEFE0D5)
val AmberSurfaceVariantDark = Color(0xFF50453A)
val AmberOnSurfaceVariantDark = Color(0xFFD4C4B5)
val AmberOutlineDark = Color(0xFF9E8E81)
